### ISSUE TITLE
Transfer to fortran-lang?

### ISSUE THREAD

**Issue by awvwgk** [awvwgk/fpm-metadata#1]
See discussion at https://github.com/fortran-lang/fpm/discussions/748

This project could be moved to @fortran-lang to officially provide a schema for the fpm package manifest. Alternatively, the files could be checked in as part of another project, *e.g.* the upstream fpm repository. Maintaining them here is of course also an option.

cc @milancurcic @certik @lkedward @gnikit

**Comment by gnikit** [comment]
I think it would make things a bit easier to maintain if it was part of fortran-lang

**Comment by milancurcic** [comment]
Thanks both. This seems like a useful package and fine with me to maintain under fortran-lang.

Consider a rename: pyfpm suggests to me a Python binding to fpm. Perhaps a more descriptive name like fpm-package-schema or fpm-package-model?

**Comment by awvwgk** [comment]
Maybe fpm-metadata, similar to the former [pep621](https://github.com/FFY00/python-pyproject-metadata) project which is now named python-pyproject-metadata.

**Comment by certik** [comment]
Fine to move. Is it because Python is easier than Fortran? :)

**Comment by awvwgk** [comment]
> Is it because Python is easier than Fortran?

The original idea was to provide Python projects a possibility to access the fpm package manifest. Candidates would be `fprettify` or `ford` should they decide to store their configuration in `fpm.toml`.

Once we decide on how to implement a schema library in Fortran the export of the schema can be provided directly by fpm (see discussion in https://fortran-lang.discourse.group/t/3963). Now that TOML Fortran has a [JSON frontend](https://github.com/toml-f/jonquil) there is the possibility to implement a schema library which is immediately usable by fpm.

In fact this would be preferable because the schema produced by the pydantic model is imperfect and does not 100% reflect the currently allowed rules in the package manifest (the biggest issue is the equivalence between underscored and dashed keywords imposed by pydantic):

```python
>>> from fpm.metadata import load_manifest
>>> load_manifest("name = 'hello'\nbuild.auto_executables = true")
Manifest(name='hello', version='0', license=None, maintainer=[], author=[], copyright=None, description=None, categories=[], keywords=[], executable=[], example=[], test=[], dependencies={}, dev_dependencies={}, extra={}, build=Build(auto_tests=True, auto_executables=True, auto_examples=True, link=[], external_modules=[]), install=Install(library=False), library=Library(source_dir='src', include_dir='include'))
```

**Comment by gnikit** [comment]
FYI I am happy with the schema generator to be in any language we find easiest to maintain, the only important thing for vscode is the final product i.e. the JSON file. I will create a pre-release of the extension using the schema for fpm validation and see how that goes.

**Comment by certik** [comment]
No, I like Python, especially with LPython now. :)

**Comment by awvwgk** [comment]
Done

**Comment by awvwgk** [comment]
If anyone has a PyPI account and needs access to the project, let me know. I also made sure (with some trial and error), that tagging a new release will automatically upload release artifacts for GitHub and PyPI.

**Comment by gnikit** [comment]
Do you think we can add `fortran-lang`'s PyPi account as a maintainer?
