### ISSUE TITLE
feat: Submit schema to JSON Schema Store

### ISSUE THREAD

**Issue by gnikit** [awvwgk/fpm-metadata#3]
To allow easy access on the schema we should submit, or setup a pipeline to auto-submit the schema to https://github.com/schemastore/schemastore/

**Comment by awvwgk** [comment]
Isn't it sufficient to reference the release URL for using the schema? This one is quite predictable and also properly versioned.

```json
{
  "$schema": "https://github.com/fortran-lang/fpm-metadata/releases/download/v0.2.1/fpm-metadata-0.2.1.json"
}
```

**Comment by gnikit** [comment]
For vscode it probably is, the problems are elsewhere (complete lack for TOML schema support). This would allow for the schema to be reachable through all the commonly used JSON schema validators. It's something that we might want to consider

**Comment by awvwgk** [comment]
Let's see whether this schema gets used first, especially considering that it not fully correct and not authoritative for fpm I would be hesitant to upload it to *schemastore* at this point.

**Comment by gnikit** [comment]
> not fully correct and not authoritative for fpm

I completely forgot about this, you are right.

As for using the schema, I am in the process of trying to figure out how to get a JSON schema to work on TOML files in VS Code. VSCode natively supports JSON and YAML, unfortunately TOML did not make the cut. The Even Better TOML **should** be able to detect schemas registered by other extensions i.e. Modern Fortran and display completions and validations but I have not been successful thus far with my efforts.

**Comment by gnikit** [comment]
I will close this and defer the conversation for a later time
